Vagrant.configure(2) do |config|
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.define :frr01 do | frr01 |
        frr01.vm.hostname = 'frr01'
        frr01.vm.network "private_network", ip: "192.168.33.13"
        frr01.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = 1
            vb.customize [
              "modifyvm", :id,
              "--hwvirtex", "on",
              "--nestedpaging", "on",
              "--largepages", "on",
              "--ioapic", "on",
              "--pae", "on",
              "--paravirtprovider", "kvm",
              "--nicpromisc1", "allow-all",
            ]
        end
          frr01.vm.synced_folder "./config/frr01 ", "/etc/frr",
          create: true, owner: "root", group: "root"
    end
    config.vm.define :frr02 do | frr02 |
        frr02.vm.hostname = 'frr02'
        frr02.vm.network "private_network", ip: "192.168.33.14"
        frr02.vm.synced_folder "./config/frr02", "/etc/frr",
          create: true, owner: "root", group: "root"
          frr02.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = 1
            vb.customize [
                "modifyvm", :id,
                "--hwvirtex", "on",
                "--nestedpaging", "on",
                "--largepages", "on",
                "--ioapic", "on",
                "--pae", "on",
                "--paravirtprovider", "kvm",
                "--nicpromisc1", "allow-all",
            ]
          end
    end
    config.vm.define :frr03 do | frr03 |
        frr03.vm.hostname = 'frr03'
        frr03.vm.network "private_network", ip: "192.168.33.15"
        frr03.vm.synced_folder "./config/frr03", "/etc/frr",
          create: true, owner: "root", group: "root"
          frr03.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = 1
            vb.customize [
              "modifyvm", :id,
              "--hwvirtex", "on",
              "--nestedpaging", "on",
              "--largepages", "on",
              "--ioapic", "on",
              "--pae", "on",
              "--paravirtprovider", "kvm",
              "--nicpromisc1", "allow-all",
            ]
          end
    end
    config.vm.provision "shell", path: "./env_init.sh"
end
